In [1]:
import tensorflow as tf
import numpy as np
import cv2
import sys, os
from skimage import io
from skimage.transform import resize
sys.path.append('..')

from src.model import Hourglass as Hourglass
import tools.inspect_checkpoint
%load_ext autoreload
%autoreload 2

In [2]:
img_path = '../demo.jpg'
out_path = '../output_colored.png'

In [3]:
img = np.float32(io.imread(img_path))
w, h = img.shape[:2]
input_height = 240
input_width = 320

In [4]:
img = cv2.resize(img, (input_width, input_height))
img = np.expand_dims(img, axis=0)

In [5]:
sample_out = io.imread('../hell0_demo_tf_320x240_prepost.png')
print(sample_out)

[[19387 18288 18064 ... 17100 17920 19150]
 [18199 18022 17715 ... 16047 16784 17208]
 [17981 17854 17523 ... 15647 16211 16806]
 ...
 [52257 53264 53628 ... 58444 58859 57767]
 [52527 53803 54187 ... 58722 58947 57918]
 [49096 53721 54102 ... 58496 58532 52894]]


In [6]:
gpus= tf.config.experimental.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(gpus[0], True)
print("Gpus are ",gpus)

Gpus are  [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [7]:
x = tf.zeros([4,384,512,3], tf.float32)

In [8]:
if gpus:
    weight_path = '../numpy_weights/weights.pkl.npy'
    #trainedWeights = np.load('weights.pkl.npy',allow_pickle=True)[()]
    print("weight loaded")
    H = Hourglass(training=False,weight_path=weight_path,normalize=True)
    print("Model created")
    H.trainable = False
    output = H.predict_on_batch(img)
    #print("output Finished",output)
    output = np.array(output, dtype=np.float32)*255
    print(output)
    io.imsave(out_path, np.array(output, dtype=np.uint8))

weight loaded
Model created
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
loading weights
[[230.06601 228.04631 227.75038 ... 235.12692 224.73686 230.45412]
 [232.04471 227.8006  228.93391 ... 226.5377  222.36766 226.4358 ]
 [235.84232 232.5685  233.39561 ... 223.662   221.49083 221.60693]
 ...
 [229.39291 228.05417 225.92091 ... 218.15771 217.13875 218.98273]
 [228.36572 225.05762 225.30272 ... 212.72368 213.78432 215.3887 ]
 [223.94109 222.36055 220.91011 ... 214.19508 213.496   217.79015]]
