In [111]:
import tensorflow as tf
import numpy as np
import cv2
import sys, os
from skimage import io
from skimage.transform import resize
sys.path.append('..')

from src.model import Hourglass as Hourglass
import tools.inspect_checkpoint
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [112]:
img_path = '../demo.jpg'
out_path = '../output_colored.png'

In [113]:
img = np.float32(io.imread(img_path))
w, h = img.shape[:2]
input_height = 240
input_width = 320

In [114]:
img = cv2.resize(img, (input_width, input_height))
img = np.expand_dims(img, axis=0)

In [115]:
sample_out = io.imread('../hell0_demo_tf_320x240_prepost.png')
print(sample_out)

[[19387 18288 18064 ... 17100 17920 19150]
 [18199 18022 17715 ... 16047 16784 17208]
 [17981 17854 17523 ... 15647 16211 16806]
 ...
 [52257 53264 53628 ... 58444 58859 57767]
 [52527 53803 54187 ... 58722 58947 57918]
 [49096 53721 54102 ... 58496 58532 52894]]


In [116]:
gpus= tf.config.experimental.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(gpus[0], True)
print("Gpus are ",gpus)

Gpus are  [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [117]:
x = tf.zeros([1,240,320,3], tf.float32)
weight_path = '../numpy_weights/weights_prepost.npy'
trainedWeights = np.load(weight_path, allow_pickle=True)[()]

In [118]:
if gpus:
    print("weight loaded")
    H = Hourglass(training=False, weightsDictionary=trainedWeights, normalize=True)
    print("Model created")
    H.trainable = False
    output = H.predict_on_batch(img)
    #print("output Finished",output)
    output = np.array(output, dtype=np.float32)*255
    # print(output)
    io.imsave(out_path, np.array(output, dtype=np.uint8))

weight loaded
32 (32,) 3/0/0/1/
32 (32,) 3/0/0/1/
32 (32,) 3/0/0/1/
32 (32,) 3/0/0/2/
32 (32,) 3/0/0/2/
32 (32,) 3/0/0/2/
32 (32,) 3/0/0/3/0/0/1/
32 (32,) 3/0/0/3/0/0/1/
32 (32,) 3/0/0/3/0/0/1/
32 (32,) 3/0/0/3/0/0/2/
32 (32,) 3/0/0/3/0/0/2/
32 (32,) 3/0/0/3/0/0/2/
32 (32,) 3/0/0/3/0/0/3/0/0/0/
32 (32,) 3/0/0/3/0/0/3/0/0/0/
32 (32,) 3/0/0/3/0/0/3/0/0/0/
64 (64,) 3/0/0/3/0/0/3/0/0/1/
64 (64,) 3/0/0/3/0/0/3/0/0/1/
64 (64,) 3/0/0/3/0/0/3/0/0/1/
32 (32,) 3/0/0/3/0/0/3/0/1/1/
32 (32,) 3/0/0/3/0/0/3/0/1/1/
32 (32,) 3/0/0/3/0/0/3/0/1/1/
32 (32,) 3/0/0/3/0/0/3/0/1/2/
32 (32,) 3/0/0/3/0/0/3/0/1/2/
32 (32,) 3/0/0/3/0/0/3/0/1/2/
32 (32,) 3/0/0/3/0/0/3/0/1/3/0/0/0/
32 (32,) 3/0/0/3/0/0/3/0/1/3/0/0/0/
32 (32,) 3/0/0/3/0/0/3/0/1/3/0/0/0/
32 (32,) 3/0/0/3/0/0/3/0/1/3/0/0/1/
32 (32,) 3/0/0/3/0/0/3/0/1/3/0/0/1/
32 (32,) 3/0/0/3/0/0/3/0/1/3/0/0/1/
32 (32,) 3/0/0/3/0/0/3/0/1/3/0/1/1/
32 (32,) 3/0/0/3/0/0/3/0/1/3/0/1/1/
32 (32,) 3/0/0/3/0/0/3/0/1/3/0/1/1/
32 (32,) 3/0/0/3/0/0/3/0/1/3/0/1/2/
32 (32,) 3/0/0

In [119]:
K = trainedWeights.keys()
# print(trainedWeights['0/conv2d/kernel'])
for k in K:
    if "conv2d" in k:
        print(k)
# print(K)

0/conv2d/bias
0/conv2d/kernel
3/0/0/1/conv2d/bias
3/0/0/1/conv2d/kernel
3/0/0/1/conv2d_1/bias
3/0/0/1/conv2d_1/kernel
3/0/0/1/conv2d_2/bias
3/0/0/1/conv2d_2/kernel
3/0/0/1/conv2d_3/bias
3/0/0/1/conv2d_3/kernel
3/0/0/1/conv2d_4/bias
3/0/0/1/conv2d_4/kernel
3/0/0/1/conv2d_5/bias
3/0/0/1/conv2d_5/kernel
3/0/0/1/conv2d_6/bias
3/0/0/1/conv2d_6/kernel
3/0/0/2/conv2d/bias
3/0/0/2/conv2d/kernel
3/0/0/2/conv2d_1/bias
3/0/0/2/conv2d_1/kernel
3/0/0/2/conv2d_2/bias
3/0/0/2/conv2d_2/kernel
3/0/0/2/conv2d_3/bias
3/0/0/2/conv2d_3/kernel
3/0/0/2/conv2d_4/bias
3/0/0/2/conv2d_4/kernel
3/0/0/2/conv2d_5/bias
3/0/0/2/conv2d_5/kernel
3/0/0/2/conv2d_6/bias
3/0/0/2/conv2d_6/kernel
3/0/0/3/0/0/1/conv2d/bias
3/0/0/3/0/0/1/conv2d/kernel
3/0/0/3/0/0/1/conv2d_1/bias
3/0/0/3/0/0/1/conv2d_1/kernel
3/0/0/3/0/0/1/conv2d_2/bias
3/0/0/3/0/0/1/conv2d_2/kernel
3/0/0/3/0/0/1/conv2d_3/bias
3/0/0/3/0/0/1/conv2d_3/kernel
3/0/0/3/0/0/1/conv2d_4/bias
3/0/0/3/0/0/1/conv2d_4/kernel
3/0/0/3/0/0/1/conv2d_5/bias
3/0/0/3/0/0/1/conv2d

In [120]:
#trainedWeights2 = np.load('../weights.pkl.npy', allow_pickle=True)[()]


In [121]:
#K = trainedWeights2.keys()
#print(K)